// <auto-generated />
using System;
using Inventorium.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventorium.API.Migrations
{
    [DbContext(typeof(InventoriumDbContext))]
    [Migration("20240706204741_InitialUpdate3")]
    partial class InitialUpdate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Inventorium.API.Models.ProductCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Inventorium.API.Models.ProductItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductReferenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductReferenceId");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("Inventorium.API.Models.ProductReferenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Discount")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("ProductReferences");
                });

            modelBuilder.Entity("Inventorium.API.Models.ProductItemModel", b =>
                {
                    b.HasOne("Inventorium.API.Models.ProductReferenceModel", "ProductReference")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductReferenceId");

                    b.Navigation("ProductReference");
                });

            modelBuilder.Entity("Inventorium.API.Models.ProductReferenceModel", b =>
                {
                    b.HasOne("Inventorium.API.Models.ProductCategoryModel", "ProductCategory")
                        .WithMany("ProductReferences")
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Inventorium.API.Models.ProductCategoryModel", b =>
                {
                    b.Navigation("ProductReferences");
                });

            modelBuilder.Entity("Inventorium.API.Models.ProductReferenceModel", b =>
                {
                    b.Navigation("ProductItems");
                });
#pragma warning restore 612, 618
        }
    }
}
